[[headers]]
  for = "/*"
  [headers.values]
    X-XSS-Protection = "1"
    Access-Control-Allow-Origin = "maximizestudios.netlify.app"
    X-Frame-Options = "deny"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer"
    Cross-Origin-Embedder-Policy = "require-corp"
    Cross-Origin-Opener-Policy = "same-origin"
    Cross-Origin-Resource-Policy = "same-origin"
    
    Permissions-Policy= '''
      accelerometer=(), 
      ambient-light-sensor=(), 
      autoplay=(), 
      battery=(), 
      camera=(), 
      display-capture=(), 
      document-domain=(), 
      encrypted-media=(), 
      execution-while-out-of-viewport=(), 
      fullscreen=(), 
      geolocation=(), 
      gyroscope=(), 
      keyboard-map=(), 
      magnetometer=(),
      microphone=(), 
      midi=(), 
      navigation-override=(), 
      payment=(), 
      picture-in-picture=(), 
      publickey-credentials-get=(), 
      screen-wake-lock=(), 
      sync-xhr=(), 
      usb=(), 
      web-share=(), 
      xr-spatial-tracking=()
    '''

    Content-Security-Policy = '''
      script-src 'none';
      child-src 'none';
      connect-src 'none';
      frame-ancestors 'none';
      base-uri 'none';
      script-src-attr 'none';
      script-src-elem 'none';
      worker-src 'none';
      manifest-src 'none';
      navigate-to 'none';
      form-action https://maximizestudios.netlify.app/;
      media-src 'none';
      object-src 'none';
      frame-src 'none';
            
      require-trusted-types-for 'script';
      
      report-uri https://maxsspot.report-uri.com/r/d/csp/enforce
    '''
